version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
    depends_on:
      - graphql-express
    ports:
      - 80:80
    volumes:
      - ./gateway/conf.d:/etc/nginx/conf.d
    restart: always
  graphql-express:
    build:
      context: ./graphql-express
      dockerfile: Dockerfile.dev
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./graphql-express/src:/app/src
    restart: always
